/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package tilemaps;

import java.awt.Canvas;
import java.awt.Color;
import java.awt.Graphics2D;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.awt.image.BufferStrategy;
import javax.swing.BorderFactory;


/**
 *
 * @author Alejandro Marrero
 */
public class VentanaPrincipal extends javax.swing.JFrame implements ActionListener {

    private boolean listo = false;
    private String nombre = "Inteligencia Artificial";
    private static Map map;
    private  static Agente jugador;
    private BufferStrategy strategy;

    public VentanaPrincipal() {
        initComponents();
        setDefaultCloseOperation(EXIT_ON_CLOSE);
        this.setTitle(nombre);
        this.setSize(1024,800);
        setResizable(false);
        this.setLocationRelativeTo(null);
        
        this.setCanvasPanel();
        botonSetup.addActionListener(this);
        botonIniciar.addActionListener(this);
        botonReset.addActionListener(this);
        
        listo = false;
        
        this.setVisible(true);
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        java.awt.GridBagConstraints gridBagConstraints;

        jOptionPane1 = new javax.swing.JOptionPane();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        obstSlider = new javax.swing.JSlider();
        jLabel3 = new javax.swing.JLabel();
        botonIniciar = new javax.swing.JButton();
        columnasSpinner = new javax.swing.JSpinner();
        filasSpinner = new javax.swing.JSpinner();
        canvasPanel = new java.awt.Canvas();
        botonSetup = new javax.swing.JButton();
        botonReset = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMaximumSize(new java.awt.Dimension(1024, 720));
        setResizable(false);

        jLabel1.setText("Filas");

        jLabel2.setText("Columnas");

        obstSlider.setValue(0);

        jLabel3.setText("Porcentaje Obstaculos");

        botonIniciar.setText("Iniciar");
        botonIniciar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonIniciarActionPerformed(evt);
            }
        });

        columnasSpinner.setValue(44);

        filasSpinner.setValue(67);

        canvasPanel.setMaximumSize(new java.awt.Dimension(1004, 663));
        canvasPanel.setMinimumSize(new java.awt.Dimension(1004, 663));
        canvasPanel.setPreferredSize(new java.awt.Dimension(1004, 663));

        botonSetup.setText("Setup");

        botonReset.setText("Reset");
        botonReset.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonResetActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel1)
                        .addGap(18, 18, 18)
                        .addComponent(filasSpinner, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jLabel2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(columnasSpinner, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(46, 46, 46)
                        .addComponent(obstSlider, javax.swing.GroupLayout.PREFERRED_SIZE, 67, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel3)
                        .addGap(32, 32, 32)
                        .addComponent(botonSetup)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(botonReset, javax.swing.GroupLayout.PREFERRED_SIZE, 79, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(botonIniciar, javax.swing.GroupLayout.PREFERRED_SIZE, 96, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(canvasPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(11, 11, 11)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(obstSlider, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(3, 3, 3)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(botonIniciar)
                            .addComponent(botonReset)
                            .addComponent(botonSetup)))
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(columnasSpinner, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel1)
                        .addComponent(filasSpinner, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(canvasPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void botonResetActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonResetActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_botonResetActionPerformed

    private void botonIniciarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonIniciarActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_botonIniciarActionPerformed

          
    public void setCanvasPanel(){
        
        canvasPanel.setBackground(Color.white);
        canvasPanel.createBufferStrategy(2);
        strategy = canvasPanel.getBufferStrategy();
        
         }

    public void pintarEntorno(Map map){
          
        Graphics2D g = (Graphics2D) strategy.getDrawGraphics();
           
        //Reseteamos el marco
            g.setColor(Color.white);
            g.fillRect(0,0,canvasPanel.getWidth(),canvasPanel.getHeight());
        
        
            map.pintarMapa(g);
            g.dispose();
            strategy.show();      
    }
    private void setupEntorno(){
        
        //Creamos el mapa
        if (listo == false){
        int porcentaje;
        int x = (int) filasSpinner.getValue(); 
        int y = (int)columnasSpinner.getValue();
        map = new Map(x,y);
        porcentaje = ((x*y)*obstSlider.getValue())/100;    
        map.setObstPercentage(porcentaje);
        pintarEntorno(map);  
        listo = true;
        
        }
        
        else
            System.out.println("No hay nada configurado");
    }
    
    private void onReset(){
       
        map = null;
        setupEntorno();
        listo = false;    
        
    }
    public static void main (String[] args){
            
            new VentanaPrincipal();
            
        }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton botonIniciar;
    private javax.swing.JButton botonReset;
    private javax.swing.JButton botonSetup;
    private java.awt.Canvas canvasPanel;
    private javax.swing.JSpinner columnasSpinner;
    private javax.swing.JSpinner filasSpinner;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JOptionPane jOptionPane1;
    private javax.swing.JSlider obstSlider;
    // End of variables declaration//GEN-END:variables

    @Override
    public void actionPerformed(ActionEvent e) {
        
        Object o = e.getSource(); //Para identificar que boton fue el que produjo el evento
        
        if ( o == botonSetup)
            this.setupEntorno();
        if ( o == botonReset)
                this.onReset();
        else
            //Iniciar algoritmo A*
            System.out.println("Algoritmo A*");    
    
    }

}